// app/layout.tsx (Server Component by default)
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// 1. Import the Providers client component
import { Providers } from "./providers"; // Adjust path if needed

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Pisval Tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* 2. Wrap children in the Providers client component */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
